### ISSUE TITLE
Fetching from environment variable in nested structure

### ISSUE THREAD

**Issue by kostrahb** [tkanos/gonfig#7]
Would it be possible to implement initialization from environment variables to allow fetching of values from `DB_HOST` for config.Database.Host in structure like this?

```
type Database struct{
    Host string
    Port int
    /* ... */
}
type Config struct {
    DB Database
    /* ... */    
}
```

**Comment by tkanos** [comment]
Yes it is possible, but it will need to code a lot.
And gonfig was not in he beginning mean to be complex (only for some student be able to work on it)

If you want to do a PR, doing so, It's up to you.

If you want to use some more complex package, you can use the excellent project of spf13 => viper

https://github.com/spf13/viper
